# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Darius/Desktop/Y4S1/EE4218/lab1/lab1.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_auto_pc_1/zynq_design_1_auto_pc_1.xci
# IP: The module: 'zynq_design_1_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Darius/Desktop/Y4S1/EE4218/lab1/lab1.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_auto_pc_1/zynq_design_1_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/Darius/Desktop/Y4S1/EE4218/lab1/lab1.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_auto_pc_1/zynq_design_1_auto_pc_1.xci
# IP: The module: 'zynq_design_1_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Darius/Desktop/Y4S1/EE4218/lab1/lab1.srcs/sources_1/bd/zynq_design_1/ip/zynq_design_1_auto_pc_1/zynq_design_1_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_design_1_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
