# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq_design_1/zynq_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1 || ORIG_REF_NAME==zynq_design_1}]

# IP: bd/zynq_design_1/ip/zynq_design_1_processing_system7_0_0/zynq_design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_processing_system7_0_0 || ORIG_REF_NAME==zynq_design_1_processing_system7_0_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_bram_ctrl_0_0/zynq_design_1_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==zynq_design_1_axi_bram_ctrl_0_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_gpio_0_0/zynq_design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_gpio_0_0 || ORIG_REF_NAME==zynq_design_1_axi_gpio_0_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_mem_intercon_0/zynq_design_1_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_mem_intercon_0 || ORIG_REF_NAME==zynq_design_1_axi_mem_intercon_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_rst_ps7_0_100M_0/zynq_design_1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynq_design_1_rst_ps7_0_100M_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_axi_bram_ctrl_0_bram_0/zynq_design_1_axi_bram_ctrl_0_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==zynq_design_1_axi_bram_ctrl_0_bram_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_xbar_0/zynq_design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_xbar_0 || ORIG_REF_NAME==zynq_design_1_xbar_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_0/zynq_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_0 || ORIG_REF_NAME==zynq_design_1_auto_pc_0}]

# IP: bd/zynq_design_1/ip/zynq_design_1_auto_pc_1/zynq_design_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_design_1_auto_pc_1 || ORIG_REF_NAME==zynq_design_1_auto_pc_1}]

# XDC: bd/zynq_design_1/zynq_design_1_ooc.xdc
